filter:
  paths: [src/*]
  excluded_paths: [vendor/*, specs/*]
tools:
  php_sim: true
  php_changetracking: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_code_sniffer: true
