filter:
    paths: [src/*]
    excluded_paths: [vendor/*, specs/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, specs]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, specs]
