filter:
  paths: [src/*]
  excluded_paths: [vendor/*, specs/*]
tools:
  php_sim: true
  php_changetracking: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer:
    enabled: true
    config:
      doc_comment_fixes:
        enabled: false
      verify_php_doc_comments:
        enabled: false
  sensiolabs_security_checker: true
  php_code_sniffer: true
