language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

install:
  - composer install --prefer-source

script:
  - bin/peridot specs/
  - bin/peridot specs/ -r clover-code-coverage --code-coverage-path build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
